/**
 * generated by Xtext 2.10.0
 */
package org.example.domainmodel;

import com.google.inject.Binder;
import com.google.inject.binder.AnnotatedBindingBuilder;
import com.google.inject.binder.LinkedBindingBuilder;
import com.google.inject.name.Named;
import com.google.inject.name.Names;
import org.eclipse.xtext.scoping.IScopeProvider;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;
import org.example.domainmodel.AbstractDomainmodelRuntimeModule;
import org.example.domainmodel.scoping.ImplicitImportsScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class DomainmodelRuntimeModule extends AbstractDomainmodelRuntimeModule {
  @Override
  public void configureIScopeProviderDelegate(final Binder binder) {
    AnnotatedBindingBuilder<IScopeProvider> _bind = binder.<IScopeProvider>bind(IScopeProvider.class);
    Named _named = Names.named(AbstractDeclarativeScopeProvider.NAMED_DELEGATE);
    LinkedBindingBuilder<IScopeProvider> _annotatedWith = _bind.annotatedWith(_named);
    _annotatedWith.to(ImplicitImportsScopeProvider.class);
  }
}
